export const actionTypes = {
  SET_DATA: "SET_DATA",
  MOVE_UP_ON_LIST: "MOVE_UP_ON_LIST",
  MOVE_DOWN_ON_LIST: "MOVE_DOWN_ON_LIST",
  CLEAR_DATA_ITEM: "CLEAR_DATA_ITEM",
  SET_ENTERED_DATA_ITEM: "SET_ENTERED_DATA_ITEM",
  SET_CURRENT_INPUT_VALUE: "SET_CURRENT_INPUT_VALUE",
};
